apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.port }} 
    protocol: {{ .Values.protocol }} 
    targetPort: {{ .Values.targetport }} 
  selector:
    app: nginx
    tag: alpine
  type: ClusterIP
